apiVersion: debezium.io/v1alpha1
kind: DebeziumServer
metadata:
  name: my-debezium
spec:
  image: quay.io/debezium/server:2.3 # feel free to use 2.3 tag to use the latest CR
  storage: # This section is required in order to have a persistent storage (will be mounted at /debezium/data)
    type: persistent
    claimName: my-pvc # At least for now you  have to create you PVC manually
  quarkus:
    config:
      log.console.json: false
      kubernetes-config.enabled: true
      kubernetes-config.secrets: postgresql-credentials
  sink:
    type: nats-jetstream
    config:
      url: nats://nats.nats.svc.cluster.local:4222 # nats://<nats-service-name>.<nats-namespace>.svc.cluster.local:4222
      create-stream: true
      subjects: postgres.*.*
  source:
    class: io.debezium.connector.postgresql.PostgresConnector
    config:
      offset.storage.file.filename: /debezium/data/offsets.dat
      offset.flush.interval.ms: 0
      # In the Debezium server configuration, 
      # confirm that the database.hostname field is set to the fully qualified domain name (FQDN) 
      #of the PostgreSQL service in the PostgreSQL namespace. 
      #The FQDN format is <postgres-service-name>.<postgres-namespace>.svc.cluster.local
      database.hostname: postgres.postgres.svc.cluster.local
      database.port: 5432
      database.user: postgres
      database.password: postgres
      database.dbname: postgres
      topic.prefix: postgres
      schema.include.list: public
      table.include.list: public.users
     # column.include.list: public.users.name
